### PR TITLE
fix: Update ec-tuf-mirror url for RHTAP 1.2

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by Roming22** [comment]
@simonbaird @rhopp my #44 seems to have been reverted by #45. Could we fast track this new issue?

**Comment by rhopp** [comment]
Im not at pc anymore... But feel free to merge this - one question though: In the original pr you changed rekor-server url as well. Shouldn't this be done here as well?

**Comment by Roming22** [comment]
@rhopp thanks for catching it. Fixed.

**Review by simonbaird — APPROVED** [review]

**Review by simonbaird — APPROVED** [review]

**Comment by Roming22** [comment]
@flacatus @xinredhat @prietyc123 Can one of you approve this PR and make sure it gets merged? Thanks.

**Pull request merged**
