### PR TITLE
Update tuf and rekor urls for rhtap 1.2

### PR DESCRIPTION
**Pull request by Roming22**
[RHTAPINST-94](https://issues.redhat.com/browse/RHTAPINST-94)

### CODE REVIEW

**Comment by Roming22** [comment]
@simonbaird PTAL.

**Comment by simonbaird** [comment]
LGTM. I don't think the yaml lint ever passes in this repo.

**Comment by rhopp** [comment]
in the first run the pipeline failed in `rox-image-check` step.
Here's the log of that step: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-appstudio_tssc-sample-pipelines/44/pull-ci-redhat-appstudio-tssc-sample-pipelines-main-rhtap-sample-pipelines-on-pull-request/1816833882746523648/artifacts/rhtap-sample-pipelines-on-pull-request/redhat-appstudio-rhtap-gather/artifacts/pods/test-pipeline1640908_docker-build-rhtap-acs-image-check-pod_step-rox-image-check.log

**Comment by rhopp** [comment]
I checked other PR check runs and they are failing on 
```
Using rox central endpoint acs-data-co5r6r0gto4t5ui3l0r0.acs.rhcloud.com:443
Download roxctl cli
Failed to download roxctl
```
Seems like the ACS instance we are using is not available anymore. Let me change the secrets and point to another instance. I'll retrigger the tests then.

**Pull request merged**
